//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Item.Access.SqlQuery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Item.Access.SqlQuery.ItemQueries", typeof(ItemQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- =============================================  
        ///-- Author:  Manoy, Mark Andrew
        ///-- Create date:   
        ///-- Description: Adds Item.
        ///-- Updated by: 
        ///-- =============================================  
        ///BEGIN  
        ///INSERT INTO [dbo].[ItemInfo]
        ///           ([Name]
        ///           ,[Manufacturer]
        ///           ,[Cost]
        ///           ,[TypeId]
        ///           ,[SubTypeId])
        ///     VALUES
        ///           (@Name
        ///           ,@Manufacturer
        ///           ,@Cost
        ///           ,@TypeId
        ///           ,@SubTypeId)
        ///END  .
        /// </summary>
        internal static string Item_Create {
            get {
                return ResourceManager.GetString("Item_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- =============================================  
        ///-- Author:  Manoy, Mark Andrew
        ///-- Create date:   
        ///-- Description: Updates Item.
        ///-- Updated by: 
        ///-- =============================================  
        ///BEGIN  
        ///SELECT TOP 1000 [Id]
        ///      ,[Name]
        ///      ,[Manufacturer]
        ///      ,[Cost]
        ///      ,[TypeId]
        ///      ,[SubTypeId]
        ///  FROM [MARKY_20151212].[dbo].[ItemInfo]
        ///  WHERE Id = @Id
        ///END  .
        /// </summary>
        internal static string Item_Delete {
            get {
                return ResourceManager.GetString("Item_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- =============================================  
        ///-- Author:  Manoy, Mark Andrew
        ///-- Create date:   
        ///-- Description: Selects Item by Id.
        ///-- Updated by: 
        ///-- =============================================  
        ///SELECT TOP 1000 [Id]
        ///      ,[Name]
        ///      ,[Manufacturer]
        ///      ,[Cost]
        ///      ,[TypeId]
        ///      ,[SubTypeId]
        ///  FROM [MARKY_20151212].[dbo].[ItemInfo]
        ///  WHERE Id = @Id.
        /// </summary>
        internal static string Item_Detail_Select {
            get {
                return ResourceManager.GetString("Item_Detail_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- =============================================  
        ///-- Author:  Manoy, Mark Andrew
        ///-- Create date:   
        ///-- Description: Select Items.
        ///-- Updated by: 
        ///-- =============================================  
        ///SELECT TOP 1000 [Id]
        ///      ,[Name]
        ///      ,[Manufacturer]
        ///      ,[Cost]
        ///      ,[TypeId]
        ///      ,[SubTypeId]
        ///  FROM [MARKY_20151212].[dbo].[ItemInfo]
        ///  WHERE NAME LIKE &apos;%&apos; + @Name + &apos;%&apos;.
        /// </summary>
        internal static string Item_ThousandRecords_Select {
            get {
                return ResourceManager.GetString("Item_ThousandRecords_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- =============================================  
        ///-- Author:  Manoy, Mark Andrew
        ///-- Create date:   
        ///-- Description: Updates Item.
        ///-- Updated by: 
        ///-- =============================================  
        ///BEGIN  
        ///INSERT INTO [dbo].[ItemInfo]
        ///           ([Name]
        ///           ,[Manufacturer]
        ///           ,[Cost]
        ///           ,[TypeId]
        ///           ,[SubTypeId])
        ///     VALUES
        ///           (@Name
        ///           ,@Manufacturer
        ///           ,@Cost
        ///           ,@TypeId
        ///           ,@SubTypeId)
        ///END  .
        /// </summary>
        internal static string Item_Update {
            get {
                return ResourceManager.GetString("Item_Update", resourceCulture);
            }
        }
    }
}
